# Site
name: "Engineer Edgar"
description: "I break, make, and fix stuff... Usually in that order. "
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
disqus: ""
email: "edgar.montano@nyu.edu"
mailchimp-list: ""

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  edgarmontano:
    name: Edgar Montano
    site: http://edgar-montano.com
    avatar: assets/images/avatar1.jpg
    bio: "Audio Engineer, Software Engineer, and Linux Enthusiast."
    email: edgar.montano@nyu.edu
    twitter: https://twitter.com/EngineerEdgar

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: edgarmontano
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
